#!/usr/bin/env ruby

require 'pathname'
Root ||= Pathname.new(File.dirname(__FILE__)).expand_path
Dir.chdir Root.join('..').to_s

require "bundler/setup"
require "iodine/http"

# Iodine.ssl = true
# Iodine.treads = 8
# Iodine.protocol.on_http do |req, res|
# 	res.session[:count] ||= 0
# 	res.session[:count] += 1
# 	res << "Visits: #{res.session[:count]}\n\nRequest object:\n\n#{req.to_s}"
# end

# Iodine.processes = 4

Iodine.protocol.on_http { "Hello World!" }


class WSChatServer
	def initialize nickname
		@nickname = nickname || "unknown"
	end
	def on_open protocol
		@io = protocol
		@io.broadcast "#{@nickname} has joined the chat!"
		@io << "Welcome #{@nickname}, you have joined the chat!"
	end
	def on_message data
		@io.broadcast "#{@nickname} >> #{data}"
		@io << ">> #{data}"
	end
	def on_broadcast data
		@io << data
	end
	def on_close
		@io.broadcast "#{@nickname} has left the chat!"
	end
end

Iodine::Http.on_websocket { |request, response| WSChatServer.new request.params[:name]}

Process.fork do

	Iodine.ssl = true
	Iodine.port = 3030
	Iodine.protocol.on_http do |req, res|
		res.session[:count] ||= 0
		res.session[:count] += 1
		res << "Visits: #{res.session[:count]}\n\nRequest object:\n\n#{req.to_s}"
	end

end
