#!/usr/bin/env ruby

require 'pathname'
Root ||= Pathname.new(File.dirname(__FILE__)).expand_path
Dir.chdir Root.join('..').to_s

require "bundler/setup"
require "iodine/http"

# Iodine.ssl = true
# Iodine.treads = 8
# Iodine.protocol.on_http do |req, res|
# 	res.session[:count] ||= 0
# 	res.session[:count] += 1
# 	res << "Visits: #{res.session[:count]}\n\nRequest object:\n\n#{req.to_s}"
# end

# Iodine.processes = 4
Iodine.protocol.on_http { "Hello World!" }

class WSEcho
	def on_open protocol
		@io = protocol
	end
	def on_message data
		write ">> #{data}"
	end
	def on_close
	end
	def write data
		@io << data
	end
	alias :<< :write
end

Iodine.protocol.on_websocket { WSEcho.new }

# Process.fork do

# 	Iodine.ssl = true
# 	Iodine.port = 3030
# 	Iodine.protocol.on_http do |req, res|
# 		res.session[:count] ||= 0
# 		res.session[:count] += 1
# 		res << "Visits: #{res.session[:count]}\n\nRequest object:\n\n#{req.to_s}"
# 	end

# end
