#!/usr/bin/env ruby
require 'rack'
require 'iodine'

module Iodine
  # The Iodine::Base namespace is reserved for internal use and is NOT part of the public API.
  module Base
    # Command line interface. The Ruby CLI might be changed in future versions.
    module CLI

      def self.try_file filename
        return nil unless File.exist? filename
        return ::Rack::Builder.parse_file filename
      end

      def self.get_app_opts
        app, opt = nil, nil
        filename = ARGV.shift
        if filename
          app, opt = try_file filename
          app, opt = try_file "#{filename}.ru" unless opt
          unless opt
            puts "* Couldn't find #{filename}\n  testing for config.ru\n"
            app, opt = try_file "config.ru"
          end
        else
          app, opt = try_file "config.ru";
        end

        unless opt
          puts "WARNING: Ruby application not found#{ filename ? " - missing both #{filename} and config.ru" : " - missing config.ru"}."
          if Iodine::DEFAULT_HTTP_ARGS[:public]
            puts "         Running only static file service."
            opt = ::Rack::Server::Options.new.parse!([])
          else
            puts cli_parser
            exit(0);
          end
        end
        return app, opt
      end

      def self.perform_warmup
        # load anything marked with `autoload`, since autoload isn't thread safe nor fork friendly.
        Iodine.run do
          Module.constants.each do |n|
            begin
              Object.const_get(n)
            rescue Exception => _e
            end
          end
          ::Rack::Builder.new(app) do |r|
            r.warmup do |a|
              client = ::Rack::MockRequest.new(a)
              client.get('/')
            end
          end
        end
      end

      def self.call
        cli_test4help.parse!
        app, opt = get_app_opts
        perform_warmup if ARGV.index('-warmup')
        Iodine::Rack.run(app, opt)
      end
    end
  end
end

Iodine::Base::CLI.call
